-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 12:29:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mit_ct_oa_cdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mit_ct_oa_cdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mit_ct_oa_cdb` DEFAULT CHARACTER SET utf8 ;
USE `mit_ct_oa_cdb` ;

-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_list` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_list` (
  `course_code` VARCHAR(15) NOT NULL,
  `stream` INT NOT NULL,
  `regulation` INT NOT NULL,
  `semester` INT NOT NULL,
  `title` VARCHAR(55) NOT NULL,
  `credit` INT NOT NULL,
  `objectives` MEDIUMTEXT NULL,
  PRIMARY KEY (`course_code`));


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`student_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`student_list` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`student_list` (
  `reg_no` INT NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`reg_no`),
  UNIQUE INDEX `reg_no_UNIQUE` (`reg_no` ASC) );


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`staff_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`staff_list` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`staff_list` (
  `staff_id` INT NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staff_id_UNIQUE` (`staff_id` ASC) );


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_reference_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_reference_table` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_reference_table` (
  `reference_id` INT NOT NULL AUTO_INCREMENT,
  `ref_code` INT NOT NULL,
  `category` VARCHAR(30) NULL,
  `ref_name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`reference_id`),
  UNIQUE INDEX `reference_id_UNIQUE` (`reference_id` ASC) ,
  UNIQUE INDEX `ref_code_UNIQUE` (`ref_code` ASC) );


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`subj_allot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`subj_allot` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`subj_allot` (
  `sallot_id` INT NOT NULL AUTO_INCREMENT,
  `staff_id` INT NOT NULL,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `class_room` VARCHAR(15) NULL,
  `student_count` INT NULL,
  PRIMARY KEY (`sallot_id`),
  UNIQUE INDEX `sallot_id_UNIQUE` (`sallot_id` ASC) ,
  INDEX `staff_id_fk_idx` (`staff_id` ASC) ,
  INDEX `course_id_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  CONSTRAINT `staff_id_fk`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mit_ct_oa_cdb`.`staff_list` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_code_fk`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_registered_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_registered_students` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_registered_students` (
  `cregst_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `reg_no` INT NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  PRIMARY KEY (`cregst_id`),
  UNIQUE INDEX `cregst_id_UNIQUE` (`cregst_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `regno_fk_idx` (`reg_no` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC),
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  CONSTRAINT `code_fk`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regno_fk1`
    FOREIGN KEY (`reg_no`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk1`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk1`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_topic` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_topic` (
  `ctopic_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `module_num` INT NOT NULL,
  `topic_num` INT NOT NULL,
  `topic` VARCHAR(100) NOT NULL,
  `conum` INT NOT NULL,
  PRIMARY KEY (`ctopic_id`),
  UNIQUE INDEX `ctopic_id_UNIQUE` (`ctopic_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  CONSTRAINT `code_fk1`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_artimat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_artimat` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_artimat` (
  `cartimat_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `conum` INT NOT NULL,
  `costmt` VARCHAR(255) NOT NULL,
  `po1` INT NOT NULL,
  `po2` INT NOT NULL,
  `po3` INT NOT NULL,
  `po4` INT NOT NULL,
  `po5` INT NOT NULL,
  `po6` INT NOT NULL,
  `po7` INT NOT NULL,
  `po8` INT NOT NULL,
  `po9` INT NOT NULL,
  `po10` INT NOT NULL,
  `po11` INT NOT NULL,
  `po12` INT NOT NULL,
  `ps1` INT NOT NULL,
  `ps2` INT NOT NULL,
  `ps3` INT NOT NULL,
  PRIMARY KEY (`cartimat_id`),
  INDEX `code_fk_idx` (`course_code` ASC) ,
  CONSTRAINT `code_fk2`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_lessonplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_lessonplan` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_lessonplan` (
  `clp_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `actual_date` DATE NOT NULL,
  `period` INT NOT NULL,
  `course_ctopic_id` INT NOT NULL,
  `references` VARCHAR(255) NULL,
  PRIMARY KEY (`clp_id`),
  UNIQUE INDEX `clp_id_UNIQUE` (`clp_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  INDEX `topic_fk_idx` (`course_ctopic_id` ASC) ,
  CONSTRAINT `code_fk21`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk3`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk3`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `topic_fk3`
    FOREIGN KEY (`course_ctopic_id`)
    REFERENCES `mit_ct_oa_cdb`.`course_topic` (`ctopic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_attendance` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_attendance` (
  `cattend_id` INT NOT NULL,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `reg_no` INT NOT NULL,
  `date` DATE NOT NULL,
  `period` INT NOT NULL,
  `presence` CHAR NOT NULL DEFAULT 'P',
  PRIMARY KEY (`cattend_id`),
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  INDEX `regno_fk_idx` (`reg_no` ASC) ,
  CONSTRAINT `code_fk4`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk4`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk4`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regno_fk4`
    FOREIGN KEY (`reg_no`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_assessment` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_assessment` (
  `cassess_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `assess_num` INT NOT NULL,
  `question_num` VARCHAR(10) NOT NULL,
  `question_stmt` BLOB NULL,
  `question_img` VARCHAR(100) NULL,
  `blooms_level` INT NOT NULL,
  `co_num` INT NOT NULL,
  `marks` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  PRIMARY KEY (`cassess_id`),
  UNIQUE INDEX `cassess_id_UNIQUE` (`cassess_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  CONSTRAINT `code_fk5`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk5`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk5`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_assesseval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_assesseval` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_assesseval` (
  `cassesseval_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `assess_num` INT NOT NULL,
  `question_num` VARCHAR(10) NOT NULL,
  `reg_no` INT NOT NULL,
  `mark` FLOAT NOT NULL,
  PRIMARY KEY (`cassesseval_id`),
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  INDEX `regnum_fk_idx` (`reg_no` ASC) ,
  CONSTRAINT `code_fk6`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk6`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk6`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regnum_fk6`
    FOREIGN KEY (`reg_no`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_assignment` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_assignment` (
  `cassign_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  `assign_num` INT NOT NULL,
  `question_num` VARCHAR(10) NOT NULL,
  `question_stmt` BLOB NULL,
  `question_img` VARCHAR(100) NULL,
  `co_num` INT NOT NULL,
  `deadline` DATE NOT NULL,
  PRIMARY KEY (`cassign_id`),
  UNIQUE INDEX `cassign_id_UNIQUE` (`cassign_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  CONSTRAINT `code_fk7`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk7`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk7`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_assigneval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_assigneval` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_assigneval` (
  `cassigneval_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `assign_num` INT NOT NULL,
  `question_num` INT NOT NULL,
  `reg_no` INT NOT NULL,
  `mark` FLOAT NOT NULL,
  PRIMARY KEY (`cassigneval_id`),
  UNIQUE INDEX `cassigneval_id_UNIQUE` (`cassigneval_id` ASC) ,
  INDEX `code_fk_idx` (`course_code` ASC) ,
  INDEX `group_fk_idx` (`group_ref` ASC) ,
  INDEX `session_fk_idx` (`session_ref` ASC) ,
  INDEX `regnum_fk_idx` (`reg_no` ASC) ,
  CONSTRAINT `code_fk8`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk8`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk8`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regnum_fk8`
    FOREIGN KEY (`reg_no`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_cacomp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_cacomp` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_cacomp` (
  `ccacomp_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `component` VARCHAR(15) NOT NULL,
  `total_marks` INT NOT NULL,
  PRIMARY KEY (`ccacomp_id`),
  UNIQUE INDEX `cintcomp_id_UNIQUE` (`ccacomp_id` ASC) ,
  INDEX `code_fk10_idx` (`course_code` ASC) ,
  INDEX `group_fk10_idx` (`group_ref` ASC) ,
  INDEX `session_fk10_idx` (`session_ref` ASC) ,
  CONSTRAINT `code_fk10`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk10`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk10`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_internalcalc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_internalcalc` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_internalcalc` (
  `cintcalc_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `reg_no` INT NOT NULL,
  `ca` FLOAT NOT NULL,
  `midterm` FLOAT NOT NULL,
  `total_marks` FLOAT NOT NULL,
  PRIMARY KEY (`cintcalc_id`),
  UNIQUE INDEX `cintcalc_id_UNIQUE` (`cintcalc_id` ASC) ,
  INDEX `code_fk11_idx` (`course_code` ASC) ,
  INDEX `group_fk11_idx` (`group_ref` ASC) ,
  INDEX `session_fk11_idx` (`session_ref` ASC) ,
  INDEX `regnum_fk11_idx` (`reg_no` ASC) ,
  CONSTRAINT `code_fk11`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk11`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk11`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regnum_fk11`
    FOREIGN KEY (`reg_no`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_extcomp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_extcomp` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_extcomp` (
  `cextcomp_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `question_num` VARCHAR(10) NOT NULL,
  `question_co` INT NOT NULL,
  `question_mark` INT NOT NULL,
  `question_section` CHAR(1) NOT NULL,
  PRIMARY KEY (`cextcomp_id`),
  UNIQUE INDEX `cextcomp_id_UNIQUE` (`cextcomp_id` ASC) ,
  INDEX `code_fk12_idx` (`course_code` ASC) ,
  INDEX `group_fk12_idx` (`group_ref` ASC) ,
  INDEX `session_fk12_idx` (`session_ref` ASC) ,
  CONSTRAINT `code_fk12`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk12`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk12`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mit_ct_oa_cdb`.`course_extcalc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mit_ct_oa_cdb`.`course_extcalc` ;

CREATE TABLE IF NOT EXISTS `mit_ct_oa_cdb`.`course_extcalc` (
  `cextcalc_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(15) NOT NULL,
  `group_ref` INT NOT NULL,
  `session_ref` INT NOT NULL,
  `reg_num` INT NOT NULL,
  `question_num` VARCHAR(10) NOT NULL,
  `marks` FLOAT NOT NULL,
  PRIMARY KEY (`cextcalc_id`),
  UNIQUE INDEX `cextcalc_id_UNIQUE` (`cextcalc_id` ASC) ,
  INDEX `code_fk13_idx` (`course_code` ASC) ,
  INDEX `group_fk13_idx` (`group_ref` ASC) ,
  INDEX `session_fk13_idx` (`session_ref` ASC) ,
  INDEX `regno_fk13_idx` (`reg_num` ASC) ,
  CONSTRAINT `code_fk13`
    FOREIGN KEY (`course_code`)
    REFERENCES `mit_ct_oa_cdb`.`course_list` (`course_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_fk13`
    FOREIGN KEY (`group_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `session_fk13`
    FOREIGN KEY (`session_ref`)
    REFERENCES `mit_ct_oa_cdb`.`course_reference_table` (`ref_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regno_fk13`
    FOREIGN KEY (`reg_num`)
    REFERENCES `mit_ct_oa_cdb`.`student_list` (`reg_no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
